###Check HTTP
GET http://localhost:8080/v1/health


### Check CreatePost
POST http://localhost:8080/v1/posts
Content-Type: application/json

{
    "title" : "This is the title",
    "content" : "This is the content",
    "tags" : ["tag1"]
}

###Check GetID
GET  http://localhost:8080/v1/posts/7


###Check Delete
DELETE http://localhost:8080/v1/posts/3


###Check Patch
Patch http://localhost:8080/v1/posts/8
Content-Type: application/json

{
    "content" : "This is Patch change",
    "title" : "This is Patch change"
}

###Check GetUser
GET http://localhost:8080/v1/users/1


###Check Follow
PUT http://localhost:8080/v1/users/1/follow
Content-Type: application/json

{
    "user_id" : 40
}

### Check Unfollow
PUT http://localhost:8080/v1/users/40/unfollow
Content-Type: application/json

{
    "user_id" : 1
}

###Check GetFeed
GET http://localhost:8080/v1/users/feed