###Check HTTP
GET http://localhost:8080/v1/health
Authorization: Basic admin:admin


### Check CreatePost
POST http://localhost:8080/v1/posts
Content-Type: application/json

{
    "title" : "This is the title",
    "content" : "This is the content",
    "tags" : ["tag1"]
}

###Check GetID
GET  http://localhost:8080/v1/posts/7


###Check Delete
DELETE http://localhost:8080/v1/posts/3


###Check Patch
Patch http://localhost:8080/v1/posts/8
Content-Type: application/json

{
    "content" : "This is Patch change",
    "title" : "This is Patch change"
}

###Check GetUser
GET http://localhost:8080/v1/users/1


###Check Follow
PUT http://localhost:8080/v1/users/1/follow
Content-Type: application/json

{
    "user_id" : 40
}

### Check Unfollow
PUT http://localhost:8080/v1/users/40/unfollow
Content-Type: application/json

{
    "user_id" : 1
}

###Check GetFeed
GET http://localhost:8080/v1/users/feed


###Check Aunthentication User
POST http://localhost:8080/v1/authentication/user
Content-Type: application/json

{
    "email" : "xdu2814031084@gmail.com",
    "password" : "888888",
    "username" : "looksaw899"
}


###Check
PUT http://localhost:8080/v1/users/activate/39cef5a0-9621-4a72-bbaf-5fa11b53118e


###Get Token
POST http://localhost:8080/v1/authentication/token
Content-Type: application/json

{
    "email" : "xdu2814031084@gmail.com",
    "password" : "888888"
}


###加入身份验证之后的Post
###首先先要得到token
POST http://localhost:8080/v1/authentication/token
Content-Type: application/json

{
    "email" : "xdu2814031084@gmail.com",
    "password" : "888888"
}
### 之后开始发帖
POST http://localhost:8080/v1/posts
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb3BoZXJzb2NpYWwiLCJleHAiOjE3NTY2MzQwNDUsImlhdCI6MTc1NjM3NDg0NSwiaXNzIjoiZ29waGVyc29jaWFsIiwibmJmIjoxNzU2Mzc0ODQ1LCJzdWIiOjY5fQ.F3q15D_TIvop7KsPVP2WH6nrcmVB0FA91mtZLtvT1m8

{
    "title" : "This is the title",
    "content" : "This is the content",
    "tags" : ["tag1"]
}
